Initial 7.4 commit

diff --git a/base/Dockerfile b/base/Dockerfile
--- a/base/Dockerfile
+++ b/base/Dockerfile
@@ -1,15 +1,22 @@
-FROM php:7.2-apache
+FROM php:7.4-apache-buster
 MAINTAINER Corey Sewell "<corey@sewell.net.nz>"
+
 ENV DEBIAN_FRONTEND=noninteractive
 ENV PATH="/root/.composer/vendor/bin:${PATH}"
 ENV COMPOSER_ALLOW_SUPERUSER=1
 
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/bin/install-php-extensions
+
 # Install components
-RUN apt-get update -y && apt-get install -y --no-install-recommends \
+RUN set -ex \
+    && apt-get update -y \
+    && apt-get upgrade -y --no-install-recommends \
+    && apt-get install -y --no-install-recommends \
         curl \
         git-core \
         gzip \
         libcurl4-openssl-dev \
+        libzip-dev \
         libgd-dev \
         libldap2-dev \
         libmcrypt-dev \
@@ -24,82 +31,78 @@ RUN apt-get update -y && apt-get install -y --no-install-recommends \
         unzip \
         zip \
         libfreetype6-dev \
-        libjpeg62-turbo-dev && \
-    curl -sS https://silverstripe.github.io/sspak/install | php -- /usr/local/bin && \
-    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && \
-    pecl install imagick-3.4.4 && \
-    pecl install mcrypt-1.0.2 && \
-    apt-get remove -y libmagickwand-dev && \
-    apt-get install -y libmagickwand-6.q16-6 && \
-    apt-get autoremove -y && \
-    apt-get clean -y && \
-    rm -r /var/lib/apt/lists/*
+        libjpeg62-turbo-dev \
+    && curl -sS https://silverstripe.github.io/sspak/install | php -- /usr/local/bin \
+    && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer \
+    && apt-get remove -y libmagickwand-dev \
+    && apt-get install -y libmagickwand-6.q16-6 \
+    && apt-get autoremove -y \
+    && apt-get clean -y \
+    && rm -r /var/lib/apt/lists/*
 
 # Install PHP Extensions
-RUN docker-php-ext-configure intl && \
-    docker-php-ext-configure mysqli --with-mysqli=mysqlnd && \
-    docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
-    docker-php-ext-enable imagick mcrypt && \
-    docker-php-ext-install opcache && \
-    docker-php-ext-install -j$(nproc) \
-        intl \
-        ldap \
+RUN install-php-extensions \
+        bcmath \
         mysqli \
         pdo \
         pdo_mysql \
+        intl \
+        ldap \
+        gd \
         soap \
         tidy \
         xsl \
-        zip
+        zip \
+        exif \
+        gmp \
+        opcache \
+        grpc
 
-RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
-    && docker-php-ext-install gd -j$(nproc) gd
+# set recommended PHP.ini settings
+# see https://secure.php.net/manual/en/opcache.installation.php
+RUN set -eux; \
+	docker-php-ext-enable opcache; \
+	{ \
+		echo 'opcache.memory_consumption=128'; \
+		echo 'opcache.interned_strings_buffer=8'; \
+		echo 'opcache.max_accelerated_files=4000'; \
+		echo 'opcache.revalidate_freq=2'; \
+		echo 'opcache.fast_shutdown=1'; \
+	} > "$PHP_INI_DIR/conf.d/opcache-recommended.ini"
+
+# Set error handling
+RUN echo 'date.timezone = Pacific/Auckland' > "$PHP_INI_DIR/conf.d/timezone.ini" && \
+    { \
+        echo 'log_errors = On'; \
+        echo 'error_log = /dev/stderr'; \
+    } > "$PHP_INI_DIR/conf.d/errors.ini"
 
 # Apache configuration
+ENV DOCUMENT_ROOT /var/www/html/public
 RUN { \
-        echo "<VirtualHost *:80>"; \
-        echo "  DocumentRoot /var/www/html"; \
-        echo "  LogLevel warn"; \
-        echo "  ErrorLog /var/log/apache2/error.log"; \
-        echo "  CustomLog /var/log/apache2/access.log combined"; \
-        echo "  ServerSignature Off"; \
-        echo "  <Directory /var/www/html>"; \
-        echo "    Options +FollowSymLinks"; \
-        echo "    Options -ExecCGI -Includes -Indexes"; \
-        echo "    AllowOverride all"; \
+        echo '<VirtualHost *:80>'; \
+        echo '  DocumentRoot ${DOCUMENT_ROOT}'; \
+        echo '  LogLevel warn'; \
+        echo '  ServerSignature Off'; \
+        echo '  <Directory ${DOCUMENT_ROOT}>'; \
+        echo '    Options +FollowSymLinks'; \
+        echo '    Options -ExecCGI -Includes -Indexes'; \
+        echo '    AllowOverride all'; \
         echo; \
-        echo "    Require all granted"; \
-        echo "  </Directory>"; \
-        echo "  <LocationMatch assets/>"; \
-        echo "    php_flag engine off"; \
-        echo "  </LocationMatch>"; \
+        echo '    Require all granted'; \
+        echo '  </Directory>'; \
+        echo '  <LocationMatch assets/>'; \
+        echo '    php_flag engine off'; \
+        echo '  </LocationMatch>'; \
         echo; \
-        echo "  IncludeOptional sites-available/000-default.local*"; \
-        echo "</VirtualHost>"; \
-    } | tee /etc/apache2/sites-available/000-default.conf
-
-RUN echo "ServerName localhost" > /etc/apache2/conf-available/fqdn.conf
-
-RUN a2enconf fqdn && \
-    a2enmod rewrite expires remoteip cgid && \
-    usermod -u 1000 www-data && \
-    usermod -G staff www-data
-
-# PHP configuration
-RUN echo "date.timezone = Pacific/Auckland" > /usr/local/etc/php/conf.d/timezone.ini
-RUN { \
-        echo "log_errors = On"; \
-        echo "error_log = /dev/stderr"; \
-    } | tee /usr/local/etc/php/conf.d/error-logging.ini
-
-RUN { \
-        echo "opcache.revalidate_freq=0"; \
-        echo "opcache.validate_timestamps=0"; \
-        echo "opcache.max_accelerated_files=7963"; \
-        echo "opcache.memory_consumption=192"; \
-        echo "opcache.interned_strings_buffer=16"; \
-        echo "opcache.fast_shutdown=1"; \
-    } | tee /usr/local/etc/php/conf.d/opcache.ini
+        echo '  IncludeOptional sites-available/000-default.local*'; \
+        echo '</VirtualHost>'; \
+	} > /etc/apache2/sites-available/000-default.conf \
+    && echo "ServerName localhost" > /etc/apache2/conf-available/fqdn.conf \
+    && a2enmod rewrite expires remoteip headers \
+    && a2enconf fqdn \
+    && usermod -u 1000 www-data \
+    && usermod -G staff www-data
 
 EXPOSE 80
 CMD ["apache2-foreground"]
